# configure swiftlint to be clean and pragmatic
included:
  - Veyra
  - VeyraTests
  - VeyraUITests

excluded:
  - Tuist
  - Derived
  - .build

disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - multiple_closures_with_trailing_closure

identifier_name:
  min_length: 2 # allow 2-character names like xs, sm, md, lg, xl
  excluded:
    - x
    - y
    - id
    - ai

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true